# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'@param A a matrix
#'@export
inv_C <- function(A) {
    .Call(`_NewPack_inv_C`, A)
}

timesTwo <- function(x) {
    .Call(`_NewPack_timesTwo`, x)
}

