# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'inverting a matrix
#'
#'@param A a matrix
#'
#'@export
inv_C <- function(A) {
    .Call(`_NewPack_inv_C`, A)
}

#'inverting a matrix
#'
#'@param A a matrix
#'
#'
#'@export
mvnpdfoptimC <- function(x, mean, varcovM, Log = TRUE) {
    .Call(`_NewPack_mvnpdfoptimC`, x, mean, varcovM, Log)
}

#'inverting a matrix
#'
#'@param A a matrix
#'
#'@export
mvnpdfsmartC <- function(x, mean, varcoM, Log = TRUE) {
    .Call(`_NewPack_mvnpdfsmartC`, x, mean, varcoM, Log)
}

timesTwo <- function(x) {
    .Call(`_NewPack_timesTwo`, x)
}

